version: '2.1'

services:
  python3:
    build: .
    image: python3
    container_name: python3
    volumes:
      - "data_work:/home/ubuntu/work"
    #restart: always
    ports:
      - "22:22"
      - "5901:5901"
    network_mode: "host"
